# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-11-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.FileField(default='empty', upload_to='')),
                ('tamanho', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
    ]
