# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-11-01 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Produto',
        ),
    ]
